'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, FileSpreadsheet, Search, UploadCloud } from 'lucide-react';
import { supabase } from '@/lib/supabase';

type Row={id:string;selected:boolean;source:string;relation:string;parentSku:string;productType:string;title:string;sourceTitle:string;description:string;sourceBrand:string;brand:string;category:string;sku:string;asin:string;size:string;color:string;stock:string;mrp:string;price:string;hsn:string;gst:string;weight:string;length:string;width:string;height:string;image:string;seoTitle:string;seoDescription:string};
type ProductGroup={key:string;parent?:Row;variants:Row[];standalone?:Row};
type Filter='all'|'ready'|'review'|'missing';
const clean=(v:unknown)=>String(v??'').replace(/\s+/g,' ').trim();
const norm=(v:string)=>v.toLowerCase().trim().replace(/[_\s]+/g,'-');
const num=(v:unknown)=>clean(v).replace(/,/g,'').match(/\d+(?:\.\d+)?/)?.[0]||'';
const banned=/\bamazon(?:\.in|\.com)?\b/gi;
const storefront=(v:string)=>clean(v.replace(banned,'').replace(/\s{2,}/g,' '));
const titleCase=(v:string)=>v.replace(/[_-]+/g,' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase()).trim();
const desc=(title:string,type:string,color:string)=>storefront(`${title}. ${type?titleCase(type)+'. ':''}${color?`Color: ${color}. `:''}Carefully review product specifications, size and package details before publishing.`).slice(0,700);
const seo=(t:string)=>storefront(`${t} | ADHYEY BROTHERS`).slice(0,60);
const seoDesc=(t:string,d:string)=>storefront(d||`Shop ${t} from ADHYEY BROTHERS.`).slice(0,155);
const validUrl=(v:string)=>{try{return ['http:','https:'].includes(new URL(v).protocol)}catch{return false}};
function unit(v:string,u:string,kind:'weight'|'length'){const n=Number(num(v));if(!n)return'';const x=clean(u).toLowerCase();if(kind==='weight'){if(x.includes('kg'))return String(n*1000);if(x.includes('lb')||x.includes('pound'))return String(Math.round(n*453.592*100)/100);return String(n)}if(x.includes('mm'))return String(n/10);if(x.includes('inch'))return String(Math.round(n*2.54*100)/100);return String(n)}
function smartCategory(type:string,title:string,cats:string[]){const words=new Set(`${type} ${title}`.toLowerCase().replace(/[_-]/g,' ').split(/\W+/).filter(x=>x.length>2));let best='',score=0;for(const c of cats){const s=c.toLowerCase().split(/\W+/).filter(x=>x.length>2).filter(x=>words.has(x)).length;if(s>score){score=s;best=c}}return score?best:''}
function problem(r:Row){if(!r.title)return'Product name required';if(!r.category)return'Category needs review';if(r.sourceBrand&&norm(r.sourceBrand)!==norm('ADHYEY BROTHERS')&&!r.brand)return'Brand conflict needs review';if(!(Number(r.price)>0))return'Selling price required';if(Number(r.mrp||r.price)<Number(r.price))return'MRP must be ≥ price';if(!/^\d{4,8}$/.test(r.hsn))return'Verified numeric HSN required';if(r.gst===''||Number.isNaN(Number(r.gst)))return'Verified GST required';if(!validUrl(r.image))return'Image required';if(!(Number(r.weight)>0&&Number(r.length)>0&&Number(r.width)>0&&Number(r.height)>0))return'Weight + L/W/H required';return''}

export default function CatalogAutomationPreview(){
 const[rows,setRows]=useState<Row[]>([]),[files,setFiles]=useState<string[]>([]),[categories,setCategories]=useState<string[]>([]);const[parsing,setParsing]=useState(false),[error,setError]=useState(''),[filter,setFilter]=useState<Filter>('all'),[query,setQuery]=useState('');
 useEffect(()=>{supabase.from('categories').select('name').eq('is_active',true).order('display_order').then(({data})=>setCategories(data?.map(x=>x.name)||[]))},[]);
 const update=(id:string,field:keyof Row,value:string|boolean)=>setRows(p=>p.map(r=>r.id===id?{...r,[field]:value}:r));
 async function parseFiles(list:FileList|null){if(!list?.length)return;setParsing(true);setError('');try{const XLSX=await import('xlsx');const next:Row[]=[];for(const file of Array.from(list)){const wb=XLSX.read(await file.arrayBuffer(),{type:'array'});const tn=wb.SheetNames.find(n=>norm(n)==='template');if(tn){const matrix=XLSX.utils.sheet_to_json<unknown[]>(wb.Sheets[tn],{header:1,defval:'',raw:false});const hi=matrix.findIndex(r=>{const a=(r||[]).map(x=>norm(clean(x)));return a.includes('title')&&a.includes('sku')});if(hi<0)throw new Error(`${file.name}: listing headers not found.`);const h=(matrix[hi]||[]).map(clean);const ix=(...names:string[])=>h.findIndex(x=>names.map(norm).includes(norm(x)));const at=(r:unknown[],...names:string[])=>{const i=ix(...names);return i>=0?clean(r[i]):''};for(let ri=hi+3;ri<matrix.length;ri++){const r=matrix[ri]||[];const sourceTitle=at(r,'Title','Item Name'),sku=at(r,'SKU');if(!sourceTitle&&!sku)continue;const productType=at(r,'Product Type'),relation=at(r,'Parentage Level')||'Standalone',parentSku=at(r,'Parent SKU'),sourceBrand=at(r,'Brand Name'),title=storefront(sourceTitle||sku).slice(0,180),color=at(r,'Color','Color Name'),size=at(r,'Size','Size Name'),price=num(at(r,'Your Price INR','Your Price','Price')),mrp=num(at(r,'Maximum Retail Price','MRP','List Price'))||price,d=desc(title,productType,color);next.push({id:`${file.name}-${ri}-${sku}`,selected:true,source:file.name,relation,parentSku,productType,title,sourceTitle,description:d,sourceBrand,brand:sourceBrand&&norm(sourceBrand)!==norm('ADHYEY BROTHERS')?'':'ADHYEY BROTHERS',category:smartCategory(productType,title,categories),sku,asin:at(r,'Product Id','ASIN'),size,color,stock:num(at(r,'Quantity','Stock'))||'0',mrp,price,hsn:'',gst:'',weight:unit(at(r,'Package Weight','Item Package Weight'),at(r,'Package Weight Unit','Item Package Weight Unit'),'weight'),length:unit(at(r,'Item Package Length','Package Length'),at(r,'Package Length Unit'),'length'),width:unit(at(r,'Item Package Width','Package Width'),at(r,'Package Width Unit'),'length'),height:unit(at(r,'Item Package Height','Package Height'),at(r,'Package Height Unit'),'length'),image:at(r,'Main Image URL','Image URL'),seoTitle:seo(title),seoDescription:seoDesc(title,d)})}}
 else{const raw=XLSX.utils.sheet_to_json<Record<string,unknown>>(wb.Sheets[wb.SheetNames[0]],{defval:''});for(let ri=0;ri<raw.length;ri++){const m=new Map(Object.entries(raw[ri]).map(([a,b])=>[norm(a),clean(b)]));const pick=(...a:string[])=>a.map(norm).map(x=>m.get(x)).find(Boolean)||'';const sourceTitle=pick('item-name','title','product-name'),sku=pick('seller-sku','sku');if(!sourceTitle&&!sku)continue;const title=storefront(sourceTitle||sku).slice(0,180),color=pick('color'),size=pick('size-name','size'),d=desc(title,'',color),price=num(pick('price','your-price')),sourceBrand=pick('brand-name','brand');next.push({id:`${file.name}-${ri}-${sku}`,selected:true,source:file.name,relation:'Standalone',parentSku:'',productType:'',title,sourceTitle,description:d,sourceBrand,brand:sourceBrand&&norm(sourceBrand)!==norm('ADHYEY BROTHERS')?'':'ADHYEY BROTHERS',category:smartCategory('',title,categories),sku,asin:pick('asin1','asin'),size,color,stock:num(pick('quantity','stock'))||'0',mrp:num(pick('mrp','maximum-retail-price','list-price'))||price,price,hsn:'',gst:'',weight:'',length:'',width:'',height:'',image:pick('image-url','main-image-url'),seoTitle:seo(title),seoDescription:seoDesc(title,d)})}}}setRows(next);setFiles(Array.from(list).map(f=>f.name))}catch(e:any){setError(e?.message||'Could not read report files.')}finally{setParsing(false)}}
 const products=useMemo(()=>{const parents=new Map<string,Row>(),children=new Map<string,Row[]>(),standalone:ProductGroup[]=[];for(const r of rows){const rel=r.relation.toLowerCase();if(rel==='parent')parents.set(r.sku,r);else if(rel==='child'&&r.parentSku)children.set(r.parentSku,[...(children.get(r.parentSku)||[]),r]);else standalone.push({key:r.id,standalone:r,variants:[r]})}const grouped:ProductGroup[]=[];for(const[key,p]of parents)grouped.push({key,parent:p,variants:children.get(key)||[]});for(const[key,v]of children)if(!parents.has(key))grouped.push({key,parent:undefined,variants:v});return[...grouped,...standalone]},[rows]);
 const productProblem=(g:ProductGroup)=>{const base=g.parent||g.standalone||g.variants[0];if(!base)return'Invalid product';const baseIssue=problem({...base,price:base.price||g.variants[0]?.price||'',mrp:base.mrp||g.variants[0]?.mrp||'',stock:base.stock||g.variants[0]?.stock||'',weight:base.weight||g.variants[0]?.weight||'',length:base.length||g.variants[0]?.length||'',width:base.width||g.variants[0]?.width||'',height:base.height||g.variants[0]?.height||'',image:base.image||g.variants[0]?.image||''});if(baseIssue)return baseIssue;return g.variants.find(v=>problem({...v,title:base.title,category:base.category,brand:base.brand,sourceBrand:base.sourceBrand,hsn:base.hsn,gst:base.gst,image:v.image||base.image}))? 'Variant needs review':''};
 const shown=useMemo(()=>products.filter(g=>{const b=g.parent||g.standalone||g.variants[0];if(!b)return false;const p=productProblem(g),q=query.toLowerCase(),match=!q||`${b.title} ${b.sku} ${b.asin} ${g.variants.map(v=>`${v.sku} ${v.size} ${v.color}`).join(' ')}`.toLowerCase().includes(q);return match&&(filter==='all'||filter==='ready'&&!p||filter==='review'&&!!p||filter==='missing'&&!!p)}),[products,filter,query]);
 const baskets=useMemo(()=>{const m=new Map<string,ProductGroup[]>();for(const g of shown){const b=g.parent||g.standalone||g.variants[0];const key=`${b?.category||'Needs Category Review'} • ${titleCase(b?.productType||'Unclassified')}`;m.set(key,[...(m.get(key)||[]),g])}return[...m.entries()]},[shown]);const ready=products.filter(g=>!productProblem(g)).length;
 const input='w-full rounded-lg border border-blue-200 bg-blue-50 px-2 py-1.5 text-xs focus:border-blue-500 focus:outline-none',required='w-full rounded-lg border border-amber-300 bg-amber-50 px-2 py-1.5 text-xs focus:border-amber-500 focus:outline-none';
 return <main className="min-h-screen bg-[#F8F9FB] px-4 py-8 sm:px-6 lg:px-8"><div className="mx-auto max-w-[1600px] space-y-5"><div className="flex items-center gap-3"><Link href="/admin/add-product" className="flex h-10 w-10 items-center justify-center rounded-xl border bg-white"><ArrowLeft size={18}/></Link><div><h1 className="text-2xl font-black text-indigo-950">Catalog Automation Preview</h1><p className="text-sm text-gray-500">One product card → all child rows shown as variants. Preview only; database save disabled.</p></div></div>
 <section className="rounded-3xl border bg-white p-6 shadow-sm"><div className="mb-4 flex items-center gap-3"><FileSpreadsheet className="text-indigo-800"/><div><b>Upload source reports</b><p className="text-xs text-gray-500">Select both report files together. Source marketplace wording is removed from storefront content.</p></div></div><label className="flex min-h-28 cursor-pointer flex-col items-center justify-center rounded-2xl border-2 border-dashed bg-gray-50"><UploadCloud className="mb-2 text-indigo-800"/><b>{parsing?'Reading files…':files.length?`${files.length} files loaded`:'Choose report files'}</b><input type="file" multiple accept=".xlsx,.xlsm" className="hidden" onChange={e=>parseFiles(e.target.files)}/></label>{error&&<p className="mt-3 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}</section>
 {rows.length>0&&<><section className="grid gap-3 sm:grid-cols-5"><Stat label="Source rows" value={rows.length}/><Stat label="Products after grouping" value={products.length} green/><Stat label="Variants" value={products.reduce((n,g)=>n+(g.parent?g.variants.length:0),0)}/><Stat label="Ready" value={ready} green/><Stat label="Needs review" value={products.length-ready} amber/></section><section className="rounded-3xl border bg-white p-4"><div className="flex flex-wrap gap-2"><div className="relative min-w-64 flex-1"><Search size={15} className="absolute left-3 top-3 text-gray-400"/><input className="w-full rounded-xl border py-2 pl-9 pr-3 text-sm" placeholder="Search product, SKU, ASIN, parent SKU…" value={query} onChange={e=>setQuery(e.target.value)}/></div>{(['all','ready','review','missing'] as Filter[]).map(f=><button key={f} onClick={()=>setFilter(f)} className={`rounded-xl px-3 py-2 text-xs font-black ${filter===f?'bg-indigo-950 text-white':'bg-gray-100'}`}>{f==='all'?'All':f==='ready'?'Ready':f==='review'?'Needs Review':'Missing Fields'}</button>)}</div></section>
 {baskets.map(([name,groups])=><section key={name} className="space-y-3"><div className="flex justify-between rounded-2xl border bg-slate-50 p-4"><div><h2 className="font-black">{name}</h2><p className="text-xs text-gray-500">{groups.length} website products</p></div><span className="h-fit rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-800">Tax review protected</span></div>{groups.map(g=><ProductCard key={g.key} g={g} update={update} categories={categories} input={input} required={required} status={productProblem(g)}/>)}</section>)}<section className="rounded-3xl border border-indigo-200 bg-indigo-50 p-5"><b>Preview safety</b><p className="mt-1 text-sm">Nothing is saved to products, inventory, tax rules or image storage from this preview.</p></section></>}</div></main>}

function Stat({label,value,green,amber}:{label:string;value:number;green?:boolean;amber?:boolean}){return <div className={`rounded-2xl border p-4 ${green?'border-green-200 bg-green-50':amber?'border-amber-200 bg-amber-50':'bg-white'}`}><p className="text-xs text-gray-500">{label}</p><b className="text-2xl">{value}</b></div>}
function ProductCard({g,update,categories,input,required,status}:{g:ProductGroup;update:(id:string,f:keyof Row,v:string|boolean)=>void;categories:string[];input:string;required:string;status:string}){const base=g.parent||g.standalone||g.variants[0];if(!base)return null;const variants=g.parent?g.variants:g.variants;return <article className="overflow-hidden rounded-3xl border bg-white shadow-sm"><div className="grid gap-4 p-5 lg:grid-cols-[120px_1fr_280px]"><div className="flex h-28 items-center justify-center overflow-hidden rounded-2xl border bg-gray-50">{validUrl(base.image||variants[0]?.image||'')?<img src={base.image||variants[0]?.image} alt="Product preview" className="h-full w-full object-contain"/>:<span className="text-xs text-gray-400">No image</span>}</div><div><div className="mb-2 flex flex-wrap items-center gap-2"><span className="rounded-full bg-indigo-50 px-2 py-1 text-[10px] font-bold text-indigo-700">{g.parent?'Grouped product':'Standalone product'}</span>{g.parent&&<span className="text-xs text-gray-500">Parent SKU: {g.key} • {variants.length} variants</span>}</div><input className={input} value={base.title} onChange={e=>update(base.id,'title',e.target.value)}/><textarea className={`${input} mt-2 min-h-20`} value={base.description} onChange={e=>update(base.id,'description',e.target.value)}/><p className="mt-2 text-[10px] font-bold text-indigo-600">Auto SEO: {base.seoTitle}</p></div><div className="grid grid-cols-2 gap-2"><label className="text-[10px] font-bold">Brand<input className={base.brand?input:required} value={base.brand} onChange={e=>update(base.id,'brand',e.target.value)}/></label><label className="text-[10px] font-bold">Category<select className={base.category?input:required} value={base.category} onChange={e=>update(base.id,'category',e.target.value)}><option value="">Review</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label className="text-[10px] font-bold">HSN<input className={required} value={base.hsn} onChange={e=>update(base.id,'hsn',e.target.value)}/></label><label className="text-[10px] font-bold">GST %<input className={required} value={base.gst} onChange={e=>update(base.id,'gst',e.target.value)}/></label><div className="col-span-2"><span className={`rounded-full px-3 py-1 text-xs font-bold ${status?'bg-amber-100 text-amber-800':'bg-green-100 text-green-800'}`}>{status||'Ready'}</span></div></div></div>
 <div className="border-t bg-slate-50/50 p-4"><div className="mb-3 flex items-center justify-between"><b>Variants ({variants.length})</b><span className="text-xs text-gray-500">Parent is not a sellable variant</span></div><div className="overflow-x-auto"><table className="min-w-[1350px] w-full text-left text-xs"><thead><tr>{['Size','Color','SKU','Stock','Price ₹','MRP ₹','Weight g','L cm','W cm','H cm','Image','Status'].map(x=><th key={x} className="px-2 py-2">{x}</th>)}</tr></thead><tbody>{variants.map(v=>{const vp=problem({...v,title:base.title,category:base.category,brand:base.brand,sourceBrand:base.sourceBrand,hsn:base.hsn,gst:base.gst,image:v.image||base.image});return <tr key={v.id} className="border-t"><td className="p-2"><input className={input} value={v.size} onChange={e=>update(v.id,'size',e.target.value)}/></td><td className="p-2"><input className={input} value={v.color} onChange={e=>update(v.id,'color',e.target.value)}/></td><td className="p-2"><input className={input} value={v.sku} onChange={e=>update(v.id,'sku',e.target.value)}/></td><td className="p-2"><input className={input} value={v.stock} onChange={e=>update(v.id,'stock',e.target.value)}/></td><td className="p-2"><input className={v.price?input:required} value={v.price} onChange={e=>update(v.id,'price',e.target.value)}/></td><td className="p-2"><input className={v.mrp?input:required} value={v.mrp} onChange={e=>update(v.id,'mrp',e.target.value)}/></td>{(['weight','length','width','height'] as (keyof Row)[]).map(f=><td className="p-2" key={f}><input className={v[f]?input:required} value={String(v[f])} onChange={e=>update(v.id,f,e.target.value)}/></td>)}<td className="p-2"><input className={v.image?input:required} value={v.image} onChange={e=>update(v.id,'image',e.target.value)}/></td><td className="p-2"><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${vp?'bg-amber-100 text-amber-800':'bg-green-100 text-green-800'}`}>{vp?'Needs Review':'Ready'}</span></td></tr>})}</tbody></table></div></div></article>}
