import type { Metadata } from 'next';
import LegalPage from '@/components/legal/LegalPage';
import { BUSINESS_INFO } from '@/lib/business-info';

export const metadata: Metadata = {
  title: 'Terms & Conditions',
};

export default function TermsAndConditionsPage() {
  return (
    <LegalPage title="Terms & Conditions">
      <ol className="list-decimal space-y-4 pl-6">
        <li>
          This document is an electronic record in terms of the Information
          Technology Act, 2000 and the rules thereunder, as applicable, including
          amended provisions relating to electronic records. This electronic
          record is generated by a computer system and does not require physical
          or digital signatures.
        </li>

        <li>
          This document is published in accordance with applicable law and sets
          out the terms governing access to and use of
          https://www.adhyeybrothers.in/ (the &quot;Website&quot;), including related
          services made available through the Website (the &quot;Platform&quot;).
        </li>

        <li>
          The Platform is owned and operated by {BUSINESS_INFO.entity}, with its
          business address at {BUSINESS_INFO.addressLines.join(' ')} (hereinafter
          referred to as the &quot;Platform Owner&quot;, &quot;we&quot;, &quot;us&quot; or &quot;our&quot;).
        </li>

        <li>
          Your use of the Platform, services and tools is governed by these Terms
          of Use and the policies incorporated by reference. If you transact on
          the Platform, you are also subject to the policies applicable to that
          transaction. By using the Platform, you agree that these Terms and the
          applicable policies form your binding obligations with the Platform
          Owner. Any additional or conflicting terms proposed by you are rejected
          unless expressly accepted by us in writing. We may update these Terms
          when required, and you are responsible for reviewing the current
          version made available on the Website.
        </li>

        <li>
          For these Terms, &quot;you&quot;, &quot;your&quot; or &quot;user&quot; means any natural or
          legal person using or purchasing through the Platform.
        </li>

        <li>
          Accessing, browsing or otherwise using the Platform indicates your
          agreement to these Terms. Please read them carefully before proceeding.
        </li>

        <li>
          The use of the Platform and/or our Services is subject to the following
          conditions:

          <ol className="mt-3 list-decimal space-y-3 pl-6">
            <li>
              You agree to provide true, accurate and complete information during
              and after registration and remain responsible for activity carried
              out through your registered account.
            </li>
            <li>
              While we take reasonable care to keep Platform information current,
              neither we nor third parties guarantee that all information or
              materials will always be error-free, complete or suitable for every
              purpose, to the extent permitted by applicable law.
            </li>
            <li>
              Your use of the Services is at your discretion. You should assess
              whether the Services and products meet your requirements before
              placing an order.
            </li>
            <li>
              Platform content, design, layout, graphics and other intellectual
              property are owned by or licensed to us. No rights are transferred
              to you except the limited right to use the Platform in accordance
              with these Terms.
            </li>
            <li>
              Unauthorized or unlawful use of the Platform or Services may lead
              to action under these Terms and applicable law.
            </li>
            <li>
              You agree to pay the charges associated with products or Services
              ordered through the Platform.
            </li>
            <li>
              You must not use the Platform or Services for any unlawful, illegal
              or prohibited purpose.
            </li>
            <li>
              The Platform may contain links to third-party websites. Your use of
              those websites is governed by their respective terms and policies.
            </li>
            <li>
              By initiating a transaction, you understand that you are entering
              into a legally binding transaction with the Platform Owner for the
              applicable products or Services.
            </li>
            <li>
              You shall indemnify and hold harmless the Platform Owner and its
              representatives from claims, demands, actions or penalties arising
              from your breach of these Terms, applicable policies, law or the
              rights of a third party, to the extent permitted by law.
            </li>
            <li>
              Neither party will be responsible for failure or delay in
              performance caused by a force majeure event to the extent recognized
              by applicable law.
            </li>
            <li>
              These Terms and disputes relating to them are governed by the laws
              of India.
            </li>
            <li>
              Disputes arising out of or in connection with these Terms are
              subject to the exclusive jurisdiction of the competent courts at
              Surat, Gujarat, India.
            </li>
            <li>
              Concerns or communications relating to these Terms should be sent
              using the contact information published on the Website.
            </li>
          </ol>
        </li>
      </ol>
    </LegalPage>
  );
}
