-- Security hardening prepared on an isolated Git branch.
-- Review/apply to Supabase only after preview validation.

begin;

-- Customer directory must obey the querying user's RLS/permissions instead of
-- inheriting the view owner's privileges.
alter view public.customer_directory set (security_invoker = true);

-- Harden mutable search paths on privileged functions.
alter function public.adjust_inventory_stock(uuid, text, integer, text, text, text)
  set search_path = public, pg_temp;
alter function public.generate_order_number()
  set search_path = public, pg_temp;
alter function public.handle_new_user_signup()
  set search_path = public, pg_temp;
alter function public.process_return_qc(uuid, text, text, numeric, text, text)
  set search_path = public, pg_temp;
alter function public.mark_refund_paid(uuid, text, text, text)
  set search_path = public, pg_temp;
alter function public.assign_courier_to_shipment(uuid, uuid, text, numeric, numeric, date, text)
  set search_path = public, pg_temp;

-- Trigger-only function: remove direct API execution.
revoke all on function public.handle_new_user_signup() from public, anon, authenticated;

-- Role helper functions are required by authenticated RLS policies but should
-- not be exposed as anonymous RPC endpoints.
revoke execute on function public.get_current_user_role() from anon;
revoke execute on function public.is_accounts_staff() from anon;
revoke execute on function public.is_admin() from anon;
revoke execute on function public.is_admin_user() from anon;
revoke execute on function public.is_staff_or_admin() from anon;

-- Order numbers are generated by trusted server-side checkout logic now; the
-- legacy sequence RPC should not be callable directly from public clients.
revoke execute on function public.generate_order_number() from anon, authenticated;

-- Guest lookup is intentionally anonymous, but signed-in users use ownership
-- based order access instead.
revoke execute on function public.get_guest_order_secure(text, text, text, text) from authenticated;
grant execute on function public.get_guest_order_secure(text, text, text, text) to anon;

-- Remove superseded duplicate policies while preserving the current access
-- model. Admin write policies remain; customer ownership policies remain.
drop policy if exists "Staff and Admin can view all orders" on public.orders;
drop policy if exists "Customers can view own orders" on public.orders;
drop policy if exists "Staff and Admin can view all order items" on public.order_items;
drop policy if exists "Customers can view own order items" on public.order_items;

-- Make auth lookups init-plan friendly instead of recalculating auth.uid() for
-- each candidate row.
alter policy "Customer read own orders" on public.orders
  using ((customer_id = (select auth.uid())) or public.is_staff_or_admin());
alter policy "Customer insert own orders" on public.orders
  with check ((customer_id = (select auth.uid())) or public.is_staff_or_admin());
alter policy "Read order items" on public.order_items
  using (exists (
    select 1 from public.orders
    where orders.id = order_items.order_id
      and (orders.customer_id = (select auth.uid()) or public.is_staff_or_admin())
  ));
alter policy "Profiles select own or staff" on public.profiles
  using ((id = (select auth.uid())) or public.is_staff_or_admin());
alter policy "Profiles update own" on public.profiles
  using (id = (select auth.uid()))
  with check (id = (select auth.uid()));
alter policy "Read returns" on public.returns
  using (
    customer_id = (select auth.uid())
    or exists (
      select 1 from public.orders
      where orders.id = returns.order_id
        and orders.customer_id = (select auth.uid())
    )
    or public.is_staff_or_admin()
  );
alter policy "Insert return request" on public.returns
  with check (
    exists (
      select 1 from public.orders
      where orders.id = returns.order_id
        and orders.customer_id = (select auth.uid())
    )
    or public.is_staff_or_admin()
  );
alter policy "Read return items" on public.return_items
  using (exists (
    select 1 from public.returns
    where returns.id = return_items.return_id
      and (returns.customer_id = (select auth.uid()) or public.is_staff_or_admin())
  ));
alter policy "Insert return items" on public.return_items
  with check (
    exists (
      select 1 from public.returns
      where returns.id = return_items.return_id
        and (returns.customer_id = (select auth.uid()) or public.is_staff_or_admin())
    )
    or public.is_staff_or_admin()
  );
alter policy "Customer read shipments" on public.shipments
  using (exists (
    select 1 from public.orders
    where orders.id = shipments.order_id
      and (orders.customer_id = (select auth.uid()) or public.is_staff_or_admin())
  ));
alter policy "Customer read tracking events" on public.shipment_tracking_events
  using (exists (
    select 1
    from public.shipments
    join public.orders on orders.id = shipments.order_id
    where shipments.id = shipment_tracking_events.shipment_id
      and (orders.customer_id = (select auth.uid()) or public.is_staff_or_admin())
  ));
alter policy "Allow admin manage storefront_filter_settings" on public.storefront_filter_settings
  using (exists (
    select 1 from public.profiles
    where profiles.id = (select auth.uid())
      and profiles.role in ('admin'::public.user_role, 'super_admin'::public.user_role)
  ))
  with check (exists (
    select 1 from public.profiles
    where profiles.id = (select auth.uid())
      and profiles.role in ('admin'::public.user_role, 'super_admin'::public.user_role)
  ));

commit;
