import { NextResponse } from 'next/server';

import { getPhonePeClient } from '@/lib/phonepe/client';

export const runtime = 'nodejs';

interface RouteContext {
  params: Promise<{
    merchantOrderId: string;
  }>;
}

export async function GET(
  _request: Request,
  context: RouteContext
) {
  try {
    const { merchantOrderId } = await context.params;
    const cleanMerchantOrderId = String(merchantOrderId || '').trim();

    // Only accept IDs generated by our create-payment route. This prevents the
    // endpoint from becoming a generic PhonePe order-status oracle.
    if (!/^PP-\d{10,16}-[A-Z0-9]{12}$/.test(cleanMerchantOrderId)) {
      return NextResponse.json(
        { success: false, error: 'Invalid merchant order ID.' },
        { status: 400 }
      );
    }

    const client = getPhonePeClient();
    const response = await client.getOrderStatus(cleanMerchantOrderId);

    // Do not expose the provider's raw response to the browser. The checkout
    // only needs the normalized state; finalization independently verifies the
    // payment server-side before creating an order.
    return NextResponse.json({
      success: true,
      merchantOrderId: cleanMerchantOrderId,
      state: response?.state ?? null,
    });
  } catch (error: unknown) {
    console.error('[PHONEPE_STATUS_ERROR]', error);

    return NextResponse.json(
      {
        success: false,
        error: 'Unable to verify PhonePe payment status.',
      },
      { status: 500 }
    );
  }
}
